### ISSUE TITLE
Plugins have to be able to set page header information

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#1002]
Jira issue originally created by user @liwo:

A plugin has to have the possiblity to add meta tags, javascripts or css includes in the head section of a page. This is currently not possible, as the head part is already rendered when the plugin gets called.

 Jira-URL: https://jira.neos.io/browse/NEOS-536

**Comment by kitsunet** [comment]
This has been fixed a while ago and headers are now transferred to the parent request in the `PluginImplementation`. Closing

**Comment by aertmann** [comment]
That doesn't really solve this issue though as it's about adding stuff to the `<head>` tag, not adding HTTP headers.

However this is a complex issue since plugins can be inserted multiple times per page, it influences caching etc. Thus the way to solve it is to use Fusion to detect if a page contains a plugin node and if so, add necessary tags to the rendered page. Without a standardized way of generating the `<head>` and `<body>` parts, a solution won't really be possible and so far flexibility has been prioritized.
