### ISSUE TITLE
Node migrate won't RemoveProperty when it set to null

### ISSUE THREAD

**Issue by Chhunlong** [neos/neos-development-collection#1174]
I had a problems with node migrate when I set transformation to 'RemoveProperty'. It does not work in case the property stored null in the database 

```
{
   "excludeTitle": null
}
```

Neos: 2.0.14
Flow: 3.0

I think if the problem can be resolve when remove property is set null. 
The node:repair will also be removed to. Thanks for your effort!

**Comment by kitsunet** [comment]
It's indeed a problem of `isset`, unfortunately not only in the `RemoveProperty` transformation but in

`\TYPO3\TYPO3CR\Domain\Model\AbstractNodeData::hasProperty()`

Should probably be fixed there.

**Comment by aertmann** [comment]
Fixed in `RemoveProperty` of `AbstractNodeData` a long time ago https://github.com/neos/neos-development-collection/commit/16280e5de6709609ad548cf60b92581eed7d7d09.

But still needs to be fixed in https://github.com/neos/neos-development-collection/blob/2.2/TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/AbstractNodeData.php#L221
