### ISSUE TITLE
Symlink issue at time of instaling neos in windos 10

### ISSUE THREAD

**Issue by anamGitHub** [neos/neos-development-collection#1198]
### Description

Hello all,
I am installing Neos Typo3 . I follow this link http://neos.readthedocs.io/en/stable/GettingStarted/Installation.html
to install neos.
I installed latest version of compaser.phar
When I run the setup it shows the installing popup but, after a bit it throws error and stop setup.
Thanks in advance.
#### Expected behavior

Install completely
#### Actual behavior

It gives error of symlink
![error_neos](https://cloud.githubusercontent.com/assets/22928373/19506945/2ca0a3c4-95ed-11e6-9fd6-89b991599ce5.png)
### Affected Versions

Neos: 

Flow: 

You can get this information by running `composer show` or using the package management module within Neos.

**Comment by dlubitz** [comment]
Hi, that's an known Windows issue. Nothing Neos special. 

You have to make sure your User running the Webservice has the capability to create symlinks:
http://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7

If you running commands on the cli, and your current user is a admin user, you have to run the cmd.exe as administrator. Otherwise you will get the same issues there.

For further questions you could ask on Neos Slack channel: https://neos-project.slack.com/
