### ISSUE TITLE
Fix Policy for current master

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-development-collection#1302]
For the current master the policy is broken. On a fresh installation it is not possible to add or edit content elements as an administrator. As soon as you add the editor role you are allowd to modify content

![screen shot 2016-12-08 at 09 33 42](https://cloud.githubusercontent.com/assets/769789/21003437/a8ffc43a-bd2b-11e6-91f4-a782fdfc19cd.png)

**Comment by mficzel** [comment]
I can confirm this problem but after some time the problem disappears and cannot be reproduced. 

My current suspicion is that this happens when testing on http://127.0.0.1:8081/ and switching between 2.3 and 3.0-ish Neos-versions and is related to browser caching.

I've seen an error in the js-console where the RegularExpressionValidator failed to load from this url ``http://127.0.0.1:8081/_Resources/Static/Packages/Neos.Neos/JavaScript/TYPO3.Neos/Validation/RegularExpressionValidator.js?bust=5a1661809263``

After some cache flushing and testing the console error is gone and at the same time adding content works again. I have no clue wether there is any link between those two problems.

**Comment by bwaidelich** [comment]
With a fresh master installation I can only partly reproduce the issue:
* Creating new pages works
* Editing existing content works
* Creating new content does *not* work

For example on the homepage.
The JS schema according to the browsers session storage is:
```json
"Neos.Demo:Homepage": {
    /* ... */
      "childNodes": {
        "main": {
          "type": "Neos.Neos:ContentCollection"
        },
        "teaser": {
          "type": "Neos.Neos:ContentCollection",
          "constraints": {
            "nodeTypes": {
              "*": false,
              "Neos.NodeTypes:Headline": true,
              "Neos.NodeTypes:Text": true,
              "Neos.NodeTypes:Image": true
            }
          }
        },
    /* ... */
```

so I should be able to insert new headline/text/image elements to the teaser but the button is disabled.
But I wonder why you think that this is related to the Policy, @johannessteu?

**Comment by mficzel** [comment]
Maybe i found something  … if the setting ``Neos.Neos.userInterface.loadMinifiedJavascript`` is ``true`` (wich is the default) the js will be required with the a cache buster that essentially is the md5 of the css or the js files. Since the minified js and css is not built again in master it may happen that browsers use a version from the cache wich obviously will not work. This is also the reason why some translations are missing (publish button, validation errors) … I think this can be solved by building new js and css files for master.

**Comment by bwaidelich** [comment]
Ah, good point. Can you quickly remind me how to build js/css so I can test this?

**Comment by mficzel** [comment]
Sorry i have no clue how the ember build stack works ... for me setting loadMinifiedJavascript to false helped a lot.

**Comment by bwaidelich** [comment]
Found it again http://neos.readthedocs.io/en/stable/Contribute/Code/UI.html
Testing now

**Comment by bwaidelich** [comment]
Tada, I can confirm that building CSS/JS fixes the issue for me!
