### ISSUE TITLE
body scripts get removed on backend page navigation

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-development-collection#1453]
Was originally posted here:
https://discuss.neos.io/t/neos-deletes-bodyscripts-by-navigate-throught-nodetree/2008

Neos  deletes the body scripts by navigating trough the nodetree.

I can’t find a solution until now. So i install a clean neos instance with the demo package.
Surprise! there is the same problem!

Way to reproduce it:
1. Install neos demo (or other site)
2. Login to Backend
3. Reload Browser Window
4. Check the bodyscripts after footer section with your inspector (there are three bodyscripts of demo package)
5. Navigate in the nodetree
6. Check the bodyscripts again, the three scripts are disappeared!

**Comment by kitsunet** [comment]
Ok, so apparently jQuerys nextUntil doesn't catch the `script` tags in 

Packages/Application/TYPO3.Neos/Resources/Public/JavaScript/Content/Application.js:479

Effectively removing them.

**A quick fix** in custom sites is to enclose the full body scripts part in a tag that is hidden via CSS. This tag is then picked up by the JS and reincluded after the AJAX load.

**Comment by KlickUndKlar** [comment]
What you mean with hidden? I tried "display: none" and "visibility:hidden". Both fail. The whole div is empty after AJAX request. 

`<div class="neos-bodyscript-hotfix">`
scripts...
`</div>`

`.neos-bodyscript-hotfix {
    visibility: hidden;
    display: none;
}`

Do i have to reinclude the scripts by my self or is that a job done by neos?

**Comment by KlickUndKlar** [comment]
Now i move the bodyscripts to the end of the body by js. So neos doesn't touch them by loading a page asynchron anymore. 
But they're not initialized after ajax request. No idea how to do this. 

`<div class="neos-bodyscript-hotfix">`
scripts...
`</div>`
`<script>`
`$(document).ready(function() {`
			`$('.neos-bodyscript-hotfix').appendTo(document.body);`
		`});`
`</script>`

Hope you find a solution soon guys. In my eyes that's a major bug because it breaks the whole backend of my clients. Is there a possibility to prevent this issue by using require JS?

**Comment by aertmann** [comment]
To share some insights here, this is nothing new and has been like this since before the first alpha. It's jQuery that prevents inserting scripts loaded via AJAX into the DOM for security reasons.

Instead of relying on scripts in the body being executed when navigating in the backend, try to bundle the JS in a way it always included and use the `Neos.PageLoaded` JS event to trigger scripts if the newly loaded content matches. See https://neos.readthedocs.io/en/stable/ExtendingNeos/InteractionWithTheNeosBackend.html

Lastly the new UI won't have this issue since it's using an iframe where security isn't an issue and scripts are executed when the iframe url is updated.

Gonna close this as a won't fix, unless someone has a compelling argument on how to achieve it without breaking existing sites and without any security concerns.

**Comment by KlickUndKlar** [comment]
My workaround looks like that:

*Template:*
```
<div class="neos-bodyscript-hotfix">
    bodyscripts..
</div>
<script>
    $(document).ready(function() {
        $('.neos-bodyscript-hotfix').appendTo(document.body);
    });
</script>
```

*Main Script:*
```
var MyJsObject = MyJsObject || {};

MyJsObject = {
    _: function() {
        ...
    }
}

MyJsObject._();

if (typeof document.addEventListener === 'function') {
    document.addEventListener('Neos.PageLoaded', function(event) {
        MyJsObject._();
    }, false);
}
```

Hope that helps other guy's with the same problem.
