### ISSUE TITLE
Asset usage broken on CLI

### ISSUE THREAD

**Issue by radmiraal** [neos/neos-development-collection#1689]
### Description

The AssetUsageInNodeProperties checks if a node is accessible and creates a context based on the current users workspace. On CLI this workspace does not exist causing a 'calling method ->getName() on null' on Packages/Application/Neos.Neos/Classes/Domain/Strategy/AssetUsageInNodePropertiesStrategy.php:100

### Steps to Reproduce

1. Remove an asset or change a node using an asset (kicks in the ContentCacheFlusher) on the CLI

#### Expected behavior

Depends, on asset remove it should be blocked. In my case I was working on an import of media which just broke because of the isInUse() call in the ContentCacheFlusher. In that case I'd expect the node would be registered as being changed.

#### Actual behavior

Call to a member function getName() on null

  Type: Error
  File: /tmp/Development/SubContextDocker/Cache/Code/Flow_Object_Classes/Neos_Neos_
        Domain_Strategy_AssetUsageInNodePropertiesStrategy.php
  Line: 100

### Affected Versions

Neos: tested 3.1 and 3.2, but probably there since the asset usage strategies were introduced

**Comment by davidspiola** [comment]
Hi! 
I debugged it a bit on a project where we get the same/similar error. The reason seems to be, that the asset is used in an unpublished user workspace I can't access. It's not just related to cli. 

I can't edit, delete, replace the asset in media manager because the getUsageReferences method in the strategy fails if the $accessible conditions is false.  Further investigating led to the NodeFactory::createFromNodeData method with returns null, validated by filterNodeByContext() method. 

Unfortunately I don't know how to fix this, but I guess is a general issue.

**Comment by kdambekalns** [comment]
Solved with https://github.com/neos/neos-development-collection/pull/1762, no?

**Comment by davidspiola** [comment]
FMPOV, yes

**Comment by radmiraal** [comment]
I assume yes ;)
