### ISSUE TITLE
Image is broken when replacing the asset

### ISSUE THREAD

**Issue by iseries** [neos/neos-development-collection#2061]
**Description**
Image is broken / not shown correctly when replacing an image (via the Neos Media Browser), which is already used. After replacing the Image it is broken on the site.
It will only shown correctly after delete the production cache manually.

![preview](https://user-images.githubusercontent.com/6272363/39822120-18e3b9ee-53aa-11e8-90f2-ba3086959644.gif)

**Steps to Reproduce**
- Make sure to enable production context.
- Add an Image to any nodeType with an image property and Publish -> Image will appear on the site. 
- Open the Neos Media Browser and replace this image with any other image.
- Close the media browser and refresh the page -> you will see a broken image.

**Expected behavior**
After replacing the image, it should be automatically replaced on every nodetype where it is used. 

**Actual behavior**
Once replaced, the new asset will be replaced in the media browser but not on every node type where it is used. The asset is broken. You have to clear the cache manually to display the image on the page.

**Affected Versions**
Flow/5.0 Neos/4.0 (same in 3.3.8 and 3.3.9)
PHP/7.2.5  

**Note**
Thanks to [Marv S](https://github.com/taeq) who found this bug

**Comment by kdambekalns** [comment]
@kitsunet Sounds like the issue we talked about today, no?

**Comment by kitsunet** [comment]
Yes and I just found out why and possibly how to fix this.

So what happens is we find asset usages, take the node identifier(s) of those asset usages and flush by tag with the identifier and node type. BUT that alone isn't sufficient because in case of a content node you possibly don't have a cache entry for that identifier to flush. Looking at the `registerNodeChange` method in the flusher reveals that that goes upwards the node hierarchy and flushes also on the DescendantOf for all parents, by that the content collection or page will finally be flushed and everything works. So the fix would be to actually get a node from the usage and then trigger a node change to produce the same flush behaviour in both cases.

**Comment by DrillSergeant** [comment]
My customer offers to sponsor 1h work if this could get fixed soonish (for his Neos 3.3). Can this help or is way more work?

**Comment by TheLalaMan** [comment]
+1 for fixing this, we experience the same Problem in our Neos 3.3 instance!
