### ISSUE TITLE
Activate Vimeo Psalm for the neos-development-collection

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#2680]
Psalm is a static code analyzer and already enabled for the flow-development-collection. It revealed lots of bugs and code-smells there already and helps finding side-effects when refactoring.

**Comment by daniellienert** [comment]
@albe 😘

**Comment by albe** [comment]
Definitely! :) Still collecting a few lessons from experience with Flow, but overall things seem to look relatively well overall. It adds a new thing for team members/maintainers to know about in order to get some PRs green, but the amount of subtle bugs it uncovers is worth it IMO. ❤️ 
If no one else starts doing this, I'll probably play around with it some time after the Release

**Comment by albe** [comment]
So some things we learned so far from psalm in Flow:
- helps a great lot in refactoring code more safely, as it detects subtle typing gotchas
- still sometimes it nags about things that are not actually wrong, which can be a hinderance
- sometimes a failing psalm check prevents a whole lot of PRs from becoming green until someone gets around to fix it in the base branch
- running psalm locally sometimes leads to different baseline files (due to slightly different psalm versions), so fixing errors should optimally happen through a pipeline

**Comment by albe** [comment]
Another important finding:
- psalm minor updates often contain changes and new checks, that will cause check failures "out of a sudden" if psalm version is not constrained
- if psalm version is constrained and only updated in higher versions, this could lead to upmerge issues with the baselines, hence I'd go for "always only update within lowest maintained"
- we could theoretically make travis update the baseline (semi-)automatically on merge commits with psalm failures (see https://github.com/neos/flow-development-collection/pull/1960)

**Comment by mhsdesign** [comment]
We actually went with phpstan for now in Neos 9.0 and Flow 8.3 and 9.0 and im currently preparing to introduce it to Neos 8.3 as well.
