### ISSUE TITLE
Neos Fusion translation with placeholder dont work

### ISSUE THREAD

**Issue by breadlesscode** [neos/neos-development-collection#3039]
### Description

It isnt possible to use Translations with placeholders in Fusion. The output of the following line is always`ABC`:

https://github.com/breadlesscode/neos-translation-bug/blob/master/DistributionPackages/Neos.TestSite/Resources/Private/Fusion/Root.fusion#L19

### Steps to Reproduce

1. Checkout this repo: https://github.com/breadlesscode/neos-translation-bug
2. Run composer install 
3. Create a site
4. See the output

#### Expected behavior

The output shows `pre demo TEST post demo`.

https://github.com/breadlesscode/neos-translation-bug/blob/master/DistributionPackages/Neos.TestSite/Resources/Private/Translations/en/Main.xlf

#### Actual behavior

The output shows `ABC`.

### Affected Versions

Neos: 4.3.15 / 5.x
Flow: 5.3.16 / 6.x
PHP: 7.3.19

**Comment by Kleisli** [comment]
Is this still an issue? For me it works like that in a current project (Neos 8.1 and PHP 8.1), I used the DataStructure, because the arguments are not just strings and I have to calculate them.

```
prototype(My.Package:MyPrototype) < prototype(Neos.Fusion:Component) {
    arguments = Neos.Fusion:DataStructure {
        arg = 'test'
    }
    renderer = ${I18n.translate('translation.id', null, props.arguments, 'Main', 'My.Package')}
}
```

**Comment by jonnitto** [comment]
I think the problem is more that you use a named argument (`0`), which is an index-like argument. 

If you want to use the argument index based (`{0}` in the `xlf` file), you should write it like this  
`${I18n.translate('demo', 'ABC', ['TEST'], 'Main')}`. 

But if you want to pass it as a named argument (`{yourkeyhere}`  in the `xlf` file) you should write  
`${I18n.translate('demo', 'ABC', {yourkeyhere: 'TEST'}, 'Main')}`

Read more about this [here](https://mind-the-seb.de/blog/the-translation-helper-in-neos-cms#headline-a3ede282-1b3c-4161-815f-f6ed263e750f)

Also, in your xlf file `product-name="Neos.TestSite"` is missing. I also would recommend it to provide also the package name in the Eel helper, just to make sure it catches the right package
