### ISSUE TITLE
Make login controller view configurable using Views.yaml

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#3041]
When one needs to extend the backend login (e.g. to add some SSO login), this could be done for Neos 3 and 4 by overriding settings in `Views.yaml`.

But with Neos 5 the backend login has been transformed to Fusion and therefore it is no longer possible to simply edit the `Views.yaml` and set a template path. There should be a way to do that…

**Comment by bwaidelich** [comment]
*Note:* I just created this issue from the already existing PR (#3009). I Don't really know the story behind this

**Comment by Lemmork** [comment]
This feature allows in an easy way to add elements to the login page. In my case, our agency is in charge for 50+ Neos Website Backends and I need to add a single-signon-button (Google oAuth2 login). With this feature you can add a new fusionPath via Views.yaml.
By the way, this is not really a new feature, because it was possible to use the Views.yaml in earlier versions like Neos3 and Neos4.

**Comment by bwaidelich** [comment]
> By the way, this is not really a new feature, because it was possible to use the Views.yaml in earlier versions

Ah, that's an important fact!
Can we find out what change led to the regression and turn this into a bugfix then?

**Comment by Lemmork** [comment]
The backend login has been transformed to fusion instead of fluid templates. Sebastian rewrote it. I had a conversation concerning that on slack (https://app.slack.com/client/T04HF7TKV/C050C8FEK/thread/C050C8FEK-1591342480.403800)
