### ISSUE TITLE
Wrong NodeType Constraints for ContentCollections with selectively allowed abstract node types

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#3212]
### Description

With #2715 the NodeType constraints of `Neos.Neos:ContentCollection` nodes was changed from
```yaml
# ...
'Neos.Neos:Document': false
```
to
```yaml
# ...
'Neos.Neos:Content': true
```

That introduced a regression that unfortunately couldn't even be fixed with a provided core migration (#3164) so the change has to be reverted (as discussed with @mficzel). See below for some more details.

### Steps to Reproduce

Create a custom ContentCollection node type that only allows an abstract child node:
```yaml
'Some.Package:SomeContentCollection':
  superTypes:
    Neos.Neos:ContentCollection: true
  constraints:
    nodeTypes:
      'Neos.Neos:Content': false
      'Some.Package:SomeAbstractNodeType': true

'Some.Package:SomeAbstractNodeType':
  abstract: true
```

#### Expected behavior

Content node types with a superType of `Some.Package:SomeAbstractNodeType` can be inserted into the custom content collection.

#### Actual behavior

No node can be inserted into the content collection

### Affected Versions

Neos: master

### Background

The problem is that with the current state a node, implementing both abstract types `Neos.Neos:Content` & `Some.Package:SomeAbstractNodeType` matches both constraints:
```yaml
      'Neos.Neos:Content': false
      'Some.Package:SomeAbstractNodeType': true
```
So the behavior of those constraints depends on the resolution order..

Changing `'Neos.Neos:Content': false` to `'Neos.Neos:Content': null` would fix the issue in fact, but this value is currently not allowed by our schema and it makes the behavior a lot more complex.

### Possible (future) solutions

We decided that it is safest to revert the original change for now but in the long run we could solve it by

#### turning `Neos.Neos:ContentCollection` into an *abstract* node type

...without any constraints (other than `*: false` so that implementations can selectively allow node types)

or:

#### adding a new `Neos.Neos:Collection` base type

...without the further constraints, make that a super type of `ContentCollection` and refer to that wherever it makes sense (for custom implementations, in the Neos Ui, ...)

Or maybe r

**Comment by jonnitto** [comment]
Good that you have found this one!

**Comment by Sebobo** [comment]
Very sad this again didn't work out 😢 

But for a future solution we should also discuss `isNodeTypeAllowedByConstraints` in `NodeType`. Last time when I worked on this topic I thought the current implementation doesn't work so well with our best practises that have evolved a lot since Neos 1.0.

**Comment by bwaidelich** [comment]
> But for a future solution we should also discuss isNodeTypeAllowedByConstraints in NodeType

Can you elaborate?

**Comment by Sebobo** [comment]
@bwaidelich it's related to the calculation of the constraint distances. The following condition is what we have since the start:
```
return $constraintDistanceForTrue < $constraintDistanceForFalse ? true : false;
```

The problem is now that we often have something like this:
```
Neos.Neos:Content: false
My.Super:Constraint: true
```

So the distance for true and false is both 1 and therefore the creation is not permitted.

In the beginning everyone used this:
```
Neos.Neos:Content: false
My.Super:NodeType: true
```

Which worked fine. One could change the condition to `<=` so true is "stronger", but then we might have other issues. That's why I think there is more needed than simply switching the constraint on the collections.
Just so annoying we need the Neos UI to fix our old problem as it's the only thing keeping users from adding any kind of node to a collection.
The idea of turning the collection abstract would basically trick our algorithm IMO by moving the distance 1 further.
