### ISSUE TITLE
Adding a shortcut node leads to exception

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#3256]
When adding a shortcut node, the default target is set to "first-child-node". There is no first child node when the node was just added, so `${q(node).children('[instanceof Neos.Neos:Document]').get(0)}` returns null. 

This leads to 

![image](https://user-images.githubusercontent.com/642226/102788526-0787c280-43a3-11eb-8894-9c9f51d61072.png)

either on publish (on the Neos demo site), or immediately when the node was added on other project setups.

This is caused by `FrontendNodeRoutePartHandler::resolveShortcutNode` which throws an exception when the node could not be resolved. Unlike previous versions, this exception is not catched.

Affected: Neos 7

**Comment by bwaidelich** [comment]
OK, I could not reproduce the issue since I didn't have the `neos/redirecthandler` (or more specific the `neos/redirecthandler-neosadapter`) package installed.
That package seems to render URL to nodes as soon as they are published.

I adjusted the `FrontendNodeRoutePartHandler` such that it catches the exception and logs it, passing on the route resolution to further routes. But that only changes the exception that is thrown to
```
Could not resolve a route and its corresponding URI for the given parameters. This may be due to referring to a not existing package / controller / action while building a link or URI. Refer to log and check the backtrace for more details.
```
since no other route will handle this case by default.

I think that we'll have to fix this in `neos/redirecthandler-neosadapter` and cater for the case that no valid route exists for a given node.
In Fusion we already do that and render an empty URL for this case (see https://github.com/neos/neos-development-collection/blob/b6f85ce1c87490c82952afe100b98c4d72fd6753/Neos.Neos/Classes/Fusion/NodeUriImplementation.php#L168-L173)

**Comment by DrillSergeant** [comment]
Thanks guys for looking into this.

We have since quite some time this workaround in place (in almost all of our Neos projects) to prevent the Excecptions-Files flooding the webserver:

```
<?php
namespace Internezzo\Neos\Aspect;

use Neos\ContentRepository\Domain\Model\NodeInterface;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Aop\JoinPointInterface;

/**
 * @Flow\Aspect
 */
class ShortcutNodeResolverAspect {

    /**
     * @Flow\Around("method(Neos\Neos\Domain\Service\NodeShortcutResolver->resolveShortcutTarget())")
     * @param JoinPointInterface $joinPoint
     * @return NodeInterface
     */
    public function fallBackToParent(JoinPointInterface $joinPoint)
    {
        $result = $joinPoint->getAdviceChain()->proceed($joinPoint);
        if ($result instanceof NodeInterface) {
            return $result;
        }
        $node = $joinPoint->getMethodArgument('node');
        if (!$node instanceof NodeInterface) {
            return $result;
        }

        if (!is_null($result)) {
            return $result;
        }

        // no target was found was found, let's fallback to the parent node (which for sure exits)
        return $node->getParent();

    }
}
```

It is just a workaround, never had the time to dig into that.

**Comment by bwaidelich** [comment]
@DrillSergeant Thanks for your input. I briefly discussed this topic with @daniellienert and it's a but "unfortunate" that we currently produce an invalid state by default when creating a shortcut node.
But to me it feels weird to silently fallback to the parent node in that case. (even though your hotfix makes a lot of sense of course!)

After digging into this, here's what I suggest to do about it:

1. Adjust the `FrontendNodeRoutePartHandler` such that it swallows (and logs) the exception as mentioned above
2. "Fix" the `neos/redirecthandler-neosadapter` package such that it can deal with invalid shortcut nodes (or failing URL building in general)
3. Change the default target mode of shortcut nodes to parent node

I already prepared & tested changes for the first two ones (will push them as PRs asap).

Changing the default mode of shortcut nodes might be odd, since "parent node" is probably the least common mode. But it's the only one that is valid "out of the box".
Alternatively we could use "selected target" as default mode and make the target required (and add it to the creation dialog).
But I'm not sure if we can somehow make a property required depending on another property...

**Comment by bwaidelich** [comment]
OK, I addressed 1. and 2. with https://github.com/neos/neos-development-collection/pull/3269 and https://github.com/neos/redirecthandler-neosadapter/pull/53

Regarding 3. (changing the default shortcut target mode) I'm not sure any more.. "First child node" is probably the most common requirement. Changing it to "parent node" or "selected target" might lead to more issues than it solves
