### ISSUE TITLE
"Duplicate entry" DB constraint error on thumbnail creation

### ISSUE THREAD

**Issue by mrimann** [neos/neos-development-collection#3479]
### Description

We encountered a Neos installation in production that was throwing Exceptions at a rate that triggered monitoring alerts. After checking what's going on, we could track it down to some external bot requesting the same **page URL** twice in short interval (either within the same second or 1 second away according the logs).

To our understanding this leads to two concurrent processes being run, trying to render that page (and thumbnails) and one of them wins and the other one ends with an error upon inserting it to the database:

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '180711e4-970f-46fb-8033-b899346f4ea7-795453ccf23df5c3ce9ce81437a' for key 'neos_media_domain_model_thumbnail.UNIQ_3A163C4955FF41717F7CBA1A'
```

Since the HTTP request details are now shown a little bit nicer in the Exception files (see https://github.com/neos/flow-development-collection/issues/2548), we were able to track that down to some Facebook-Crawler in our case. So in the log this looks like this:

```
customer-name@web26:~/logs$ zgrep "/en/path/to/page" customer-name.tld_access_ssl.log.2.gz
2a03:2880:32ff:4::face:b00c - - [19/Oct/2021:16:19:16 +0200] "GET /en/path/to/page HTTP/1.1" 200 9056 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
2a03:2880:32ff:c::face:b00c - - [19/Oct/2021:16:19:16 +0200] "GET /en/path/to/page HTTP/1.1" 500 508 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
```

We tried to solve this on the webserver level by applying some kind of rate-limiting. But since the request at times are not within one second, a "1 request per second" policy would not work nicely. And applying either a "1 request per minute" or "20 requests per minute" somehow feels wrong.

Thus I'm mentioning this here, so hopefully this can be solved "at the source", within Neos/Flow.

I couldn't find any existing issue - but some mentions of this error when searching the Neos Slack for `duplicate entry thumbnail` for the last years. But either I overlooked the solution there or there was none.

### Steps to Reproduce

1. have a Neos installation with a page that is not cached (probably, I'm not yet 100% sure what needs to be in place so that the error "happens")
2. fire two requests for that page at the almost-same moment
3. examine the logs, first request will get logged as a 200 OK, the second one with a 500 error status code
4. see the Exception files

#### Expected behavior

Both requests being served properly, without rendering a status code 500 and without throwing Exceptions.

#### Actual behavior

One requests get's properly rendered and delivered, the other one get's a 500 status code and a nice error page.

### Affected Versions

Neos: 5.3.4

Flow: 6.3.13

**Comment by mrimann** [comment]
We've seen this to happen both from external calls (like Facebook hitting the same URL twice within the same second), but we've also seen this to happen for backend users according to the exception file where the following GET-Request is mentioned:
```
HTTP REQUEST:
target: /neos/content/image-with-metadata?image=c59ea559-7e30-4b48-b304-ddc6d0397c7c
```
(not sure if the user sees an error, or if the GUI is handling this properly)

**Comment by kdambekalns** [comment]
Looking into this…

**First observation**: I cannot reproduce this with frontend requests in the demo site, as no thumbnails are generated. But when opening the media browser concurrently I can see this… and with a `media:clearthumbnails` it can be reproduced with some luck.

When starting to try fixes for the other errors mentioned below, I could no longer reproduce this, though. Still need to find out if that's coincidence or not.

# More errors

## file could not be symlinked

Another error in the log that sometimes is triggered: `Exception #1415716368 in line 224 of /application/Data/Temporary/Development/SubContextBeach/SubContextInstance/Cache/Code/Flow_Object_Classes/Neos_Flow_ResourceManagement_Target_FileSystemTarget.php: Could not publish "/application/Data/Persistent/Resources/9/5/c/0/95c079b855a29d9445a957f5075d3482663b16d7" into resource publishing target "localWebDirectoryPersistentResourcesTarget" because the source file could not be symlinked at target location. - See also: 202201181025409d7053.txt` – but that can be caught with another check and ignored if the existing link points to the expected target.

## mkdir(): File exists

Yet another error seen sometimes it about a directory already existing: `Exception #1: Warning: mkdir(): File exists in /application/Packages/Framework/Neos.Utility.Files/Classes/Files.php line 251` – this is from `createDirectoryRecursively()` where the result is checked and the error ignored if the directory in fact does exist. So this is something that is only in the logs and can be ignored. A fix might be the use of `clearstatcache()` in the function…

**Comment by kdambekalns** [comment]
Without further workarounds the exception is reproducible with opening the media browser in two tabs after clearing thumbnails, no luck needed.

**Comment by kdambekalns** [comment]
Created issues for the other findings:
- https://github.com/neos/flow-development-collection/issues/2667
- https://github.com/neos/flow-development-collection/issues/2670

**Comment by kdambekalns** [comment]
Discussed that yesterday with @kitsunet @robertlemke and we concluded that "catching this" is impossible with the current code flow. Since the `Thumbnail` is created and added in mutliple processes at the same time but flushing of the UoW happens on shutdown, this cannot be handled.

The only way we came up with that does not require a queue to ensure every thumbnail creation is attempted only once at the same time is to handle storing the thumbnail instance directly using DBAL using a lock. If that fails, reading it (again) might already find it.

While this may not be 100% safe (what is, anyway), it drastically shortens the time between looking for a thumbnail and persisting it (considering many thumbnails may be generated during one request before shutdwn happens.)
