### ISSUE TITLE
Workspace Module: A restricted editor is able to click on publish selected changes to live and gets raw exceptions back

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#3615]
1. go to a (non live) workspace with changes as an restricted editor

2. observe, that as expected only `Discard all changes` is visible and the button `Publish all changes to live` is not shown for editor without access to `live`

3. select a change, and notice the unexpected `Publish selected changes` button
![image](https://user-images.githubusercontent.com/85400359/154274159-24d8781b-4016-45df-811d-53b5b0e428c7.png)

4. ensure youre alone, close the curtains and secretly hit this ominous button.

5. get a raw exception back
![image](https://user-images.githubusercontent.com/85400359/154274247-0636c383-595e-40b7-8d85-fbb336bb11f3.png)

-----

## expected behavior:
the in step 3 shown button is not show, if the editor has no access.

## Neos 7.3.1

**Comment by markusguenther** [comment]
Hmm, tried to reproduce that with Neos 5.3, and it does not have this issue :/

<img width="1433" alt="Screenshot 2022-02-16 at 15 27 35" src="https://user-images.githubusercontent.com/1014126/154285340-8ebc27d0-dd23-4940-aeb1-434c3c6aac12.png">

**Comment by lorenzulrich** [comment]
The problem is here: https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html#L189

The publish button has a "disabled" property if `canPublishToBaseWorkspace` is false, which is correct.

However, in the JavaScript code above, this attribute is removed as soon as a checkbox is clicked:

https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html#L118
https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html#L148

My suggestion would be to remove the "publish selected changes" button completely if you're not allowed to publish anyway. What sense does it make to unhide a link that is still disabled?

**Comment by Benjamin-K** [comment]
> funny found a duplicate: #1507

The other issue also states, that it is possible to call publish actions from the content view of Neos. Does this still apply? If not, we should add it here (as the other issue is now closed).

**Comment by mhsdesign** [comment]
This was fixed lately in the ui if i recall correctly.

Thanks @Benjamin-K for hint tough!

**Comment by crydotsnake** [comment]
Could reproduce it

![SCR-20230128-jea](https://user-images.githubusercontent.com/39345336/215267585-1852ad1b-6643-42b6-ad07-44a84c955bcf.png)
