### ISSUE TITLE
TASK: re-implement NodeSearchService

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#3771]
(see 2a9cc3bd2d3ad133b610e2b1da5ddd4a4ac04b96 where it was removed)

**Comment by mhsdesign** [comment]
in the last weekly we actually discussed that we rather want to remove this search service as the findDescendantNodes subgraph api is powerful enough.

the only gain this interface / service provides is that all places using it could possibly take advantage of an improved implementation of this interface via like elastic search. But that also means that the results may vary by implementation and we concluded that it’s not worth it.

So instead the goal is to remove service and interface.

cc @bwaidelich and original author of this draft issue @skurfuerst

**Comment by mhsdesign** [comment]
This would be a reimplementation

https://github.com/neos/neos-development-collection/pull/4554

and this would be the full removal

https://github.com/neos/neos-development-collection/pull/4555

lets decide ;)

**Comment by nezaniel** [comment]
I'm all for reimplementation; Excluding the possibility to use specialized tools like ES for really large instances makes little sense to me

**Comment by bwaidelich** [comment]
@mhsdesign thanks for the initiative – having concrete PRs makes it easier to discuss this topic!

> I'm all for reimplementation

I beg to differ, well _partly_ ;)
I'd be OK with a capable abstraction to find nodes (e.g. some kind of query builder or DSL (cypher?)) that you can replace the implementation for but IMO we don't gain anything by an interface whose default implementation is basically a one-line-wrapper around `SubgraphInterface::findDescendantNodes()` with a *worse* API.

If we look at [todays implementation](https://github.com/neos/neos-development-collection/blob/8.3/Neos.Neos/Classes/Domain/Service/NodeSearchService.php) we can see to what weirdnesses such an over-general interface can lead to:
* It is very implicit – e.g. we have to look at the implementation to understand whether multiple search terms are combined via AND or OR
* the implementation has additional parameters to satisfy edge cases
* we do some special handling of search terms that match `NodeIdentifierValidator::PATTERN_MATCH_NODE_IDENTIFIER` – which is basically matches *any string* since [6 years](https://github.com/neos/neos-development-collection/commit/d4acfcd87daac84a7dc3a5f1b60031e1b5cd9151) – other implementations will probably behave different which makes it really hard to depend on this API

To cut a long story short: I'm all for removing it until we can come up with a better interface (and IMO that doesn't even need to be part of the core)

**Comment by mhsdesign** [comment]
I totally agree with Bastian. I couldn't come up with a good interface, and when swapping out the implementation - there is no guarantee that the behavior is the same (about and vs or...).

**Comment by nezaniel** [comment]
But we already have an Interface (the subgraph one's), why not use that for now? Doesn't have to be perfect, let's ship something sensible in 9 and something better in 10

**Comment by mhsdesign** [comment]
Yes lets remove it, ill await your formal approval of https://github.com/neos/neos-development-collection/pull/4555

meanwhile ill close the reimplementation pr.

**Comment by mhsdesign** [comment]
FYI as seen in https://neos-project.slack.com/archives/C050C9FKB/p1716545105918369?thread_ts=1716291704.931399&cid=C050C9FKB there are some real cool uses of replacing the search service. So we might have to reconsider our decision or implement some other kind of extension point:

**Comment by kitsunet** [comment]
Mmmm, yeah, although you can _just_ implement somthing like it as EelHelper? I did always like it though, was a good extension point.

**Comment by mhsdesign** [comment]
We couldnt decide for a new api signature (due to new complexity of multi crs) ill think its okay for the next person to do who will really want this feature, say for Neos 9.1 - we have to make some cutbacks to get Neos 9 out at all without to much bike shedding ^^

**Comment by Sebobo** [comment]
Is there a replacement for the node search in the document tree?

My customers all use the search in the backend a ton and also via my terminal and commandbar plugins which use the same service as it was so easy to use and okayish to modify. Just some days ago I made it full text capable via the Sandstorm Kissearch in one large project. Therefore I would need definitely a replacement before I can upgrade any those projects and my plugins. Having nothing is not better than having something not so awesome which worked good enough. 

Maybe some of topics like these could be marked and discussed during the sprint? Maybe a simple solution be worked on? I would help of course.

**Comment by mhsdesign** [comment]
yeah sure feel free to readd missing extension points ;) ... we should probably discuss this in a new issue in the Neos Ui. The global `NodeSearchService` is dead.

**Comment by bwaidelich** [comment]
> yeah sure feel free to readd missing extension points

extension points should be carefully crafted and coordinated such that we don't repeat mistakes from the past.
But obviously BE search _has_ to work.
If it's broken right now I'd suggest to re-implement it using the Subgraph API for now. That should be capable and fast enough for most cases (for others, a custom package could replace the implementation and target ES or similar)

**Comment by bwaidelich** [comment]
@Sebobo FYI I just tested it and the backend search still works because it uses the weird (but still supported) FlowQuery API and the custom [SearchOperation](https://github.com/neos/neos-ui/blob/eb1448596ed5c8c3a5e06654b0f2bb204a6fffd6/Classes/FlowQueryOperations/SearchOperation.php) that internally calls
```php
Subgraph::findDescendantNodes(
    $contextNode->aggregateId,
    FindDescendantNodesFilter::create(
        searchTerm: $arguments[0],
        nodeTypes: $$arguments[1]
    )
);
```

It won't find nodes by their aggregate id though..
I added that with https://github.com/neos/neos-ui/pull/3789 (requires https://github.com/neos/neos-development-collection/pull/5098)
