### ISSUE TITLE
Improve Exception handling in Projections

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#3854]

**Comment by bwaidelich** [comment]
Maybe a simple work-around would be to create a CLI command that can show the health of a projection *just by looking at the state version and comparing that to the latest event version* (or by triggering a catchup: no new events = all fine, new events applied w/o exception = all fine, exceptions => handle).
That script could maybe update the checkpoint version somehow and (re-)trigger a catchup so that events can be skipped without us having to implement logic for that in every projection

**Comment by bwaidelich** [comment]
First part of that tool (checking state, allow catchup to be triggered) could also be put in an admin Backend module!

**Comment by bwaidelich** [comment]
This will (partially) be resolved with #4746 since with that change events are always applied in the same request. An exception during projection will still lead to an invalid state, but it will be visible immediately and stop the process – allowing to fix and replay the affected projection.
Closing for now
