### ISSUE TITLE
NodeAggregateNameWasChanged does not create copy on write

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4150]
The [DoctrineDbalContentGraphProjection](https://github.com/neos/neos-development-collection/blob/003c8e65e3413af7e22172802ab3e0b4ddb9063e/Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php#L380-L393) directly updates the hierarchyrelations without creating copies of the affected nodes first.

**Edit 12th April 2024:**
One of the issues is that the node timestamps are not updated when its name changed.
We decided to tackle this because it would require a projection replay if changed lateron.

**Comment by nezaniel** [comment]
Just to clarify so that I can write appropriate tests: What exactly are the issues here?
The content graph integrity should be intact, but there might be workspace issues?

**Comment by bwaidelich** [comment]
sorry.. what a bad bug description of mine..
And, worse, I can't remember the steps to reproduce / expected vs actual behavior..

I think the issue was, that the aggregate name is always changed in all variants

**Comment by mhsdesign** [comment]
> maybe somehow related to https://github.com/neos/neos-development-collection/issues/4942?

**Comment by nezaniel** [comment]
Node names are currently aggregate scoped, so name changes across variants are by design.
We should trigger a copy on write anyway though; This probably currently doesn't happen because names are written to the hierarchy relations

**Comment by nezaniel** [comment]
In preparation of this, I stumbled upon an issue.

Currently we have `ContentGraphInterface::findChildNodeAggregatesByName` which explicitly states that there might be multiple of those.
Then we have e.g. `TetheredNodeInternals::createEventsForMissingTetheredNode` which throws a RuntimeException in that exact case.

We have to come to a decision whether we allow multiple child node aggregates with the same name - as long as they do not share dimension space points - or not.

This can be shown with given example:

![Image](https://github.com/neos/neos-development-collection/assets/1687674/51b4df72-2414-4508-a4e7-bdbe501d84a8)

Here, we no longer can translate `nody-mc-nodeface` to violet as its name is already covered by `evil-occupier` because it takes precedence by having the same name. While `evil-occupier` might actually take the same role, this defeats the idea of node aggregates aggregating all variants of the same content.

Thus, I'd opt for enforcing unique child names on aggregate level, which would prevent us to create or move `evil-occupier` there in the first place. wdyt?

**Comment by bwaidelich** [comment]
> I'd opt for enforcing unique child names on aggregate level

I agree: if we're not 100% sure, we should take the defensive route (i.e. enforce unique child names on aggregate level) since it's easier to relax that constraint if it turns out to yield issues.
Also I think, addressing a tethered node by its name is similar to addressing a node by it's id – which can't be different per variant either
