### ISSUE TITLE
neos cms not install in proper way and many times giva same errors

### ISSUE THREAD

**Issue by Abhishek22082000** [neos/neos-development-collection#4178]
Could not publish "C:/xampp/htdocs/testneos/Data/Persistent/Resources/a/8/9/2/a8928912867a730a7d6a075984743a7b41f1e51d" into resource publishing target "localWebDirectoryPersistentResourcesTarget" because the source file could not be symlinked at target location.

Error while attempting to create a relative symlink at "C:/xampp/htdocs/testneos/Web/_Resources/Persistent/a/8/9/2/a8928912867a730a7d6a075984743a7b41f1e51d/1.jpg" pointing to "..\..\..\..\..\..\..\..\Data\Persistent\Resources\a\8\9\2\a8928912867a730a7d6a075984743a7b41f1e51d

Please help me

**Comment by bwaidelich** [comment]
Hi @Abhishek22082000,

This issue tracker is meant for bug reports and feature requests.
Please refer to our [support channels](https://www.neos.io/community/support.html) in order to get help with your Neos setup.
There are similar qustions to yours on discuss.neos.io, see https://discuss.neos.io/search?q=because%20the%20source%20file%20could%20not%20be%20symlinked

**Comment by Abhishek22082000** [comment]
How to create a class and id of neos cms

**Comment by bwaidelich** [comment]
@Abhishek22082000 did you see my message? If you use our official support channels (https://discuss.neos.io or https://slack.neos.io) and describe your issues in full sentences, chances are very good that someone can help you
