### ISSUE TITLE
9.0 Discussion nullable PropertyType `type: ?string`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4304]
Currently `null` as property value is being treated as to unset a property:
https://github.com/neos/neos-development-collection/blob/782b9585bb53f71a326c99c9fbf85671418f91ef/Neos.ContentRepository.Core/Classes/Feature/NodeModification/Event/NodePropertiesWereSet.php#L32-L33

I wonder what the idea behind this (currently dead code) implementation of `\Neos\ContentRepository\Core\Infrastructure\Property\PropertyType->isNullable` from @nezaniel was.

https://github.com/neos/neos-development-collection/blob/31cb00aa0bb513c9e8878807a0de23772f50d992/Neos.ContentRepository.Core/Classes/Infrastructure/Property/PropertyType.php#L55-L60

Do we need this in the future?

Fixed by https://github.com/neos/neos-development-collection/pull/4325

**Comment by nezaniel** [comment]
The idea was that if you want something to be nullable, you'd declare `type: ?string` explicitly, but iirc we decided to postpone this as it would be very breaky

**Comment by mhsdesign** [comment]
would this behave then as being required otherwise? Like you cant unset a non nullable property? And have to specify it at creation?

**Comment by mhsdesign** [comment]
i mean one could simply write a migration (to append a `?` to all declared types), but then again i think in the most cases you want the property to be nullable so maybe we can find a way to declare that it is required? Wait we have validators for this? But they are not triggered by the command right?

**Comment by mhsdesign** [comment]
i just talked with @bwaidelich about this and the general ideas were:

to use the following syntax:
```
type: string
required: true
```

the behavior would be, that you cannot set the property to null and the property must either be defined at creation time (via creation dialog) or must have an default value.


we thought at first to make `required: true` an alias to the not empty validator, but introducing flow's validators into the new cr is not what were are looking forward to. Validators are neither in 8.3 nor 9.0 run on the php side but only triggered by the neos ui, if they have a js-validator implementation.

A better approach to validators seem to be value objects like `type: Neos\Neos\Types\Email` which validate the constrains in the constructor.
Those value objects could be created via ajax (maybe via an own requestHandler to not boot flow? and use plain php?) and the ui could then determine in near real time if the field is valid.

Even better would be to actually trigger the cr logic directly to also validate type conflicts and also handle `required` on the server.

**Comment by bwaidelich** [comment]
> Even better would be to actually trigger the cr logic directly

IMO we should do _both_.
The UI could interpret that `required` flag and do that "not empty" logic that it does today already.
And for other (non-simple) types it could use that AJAX validation, MH described above.
In any case, `required` flag and type conversion should be tested at command handling time, before the `NodePropertiesWereSet` event is created

*Note:* We also briefly discussed support for special syntax `?string`, `!string` (or `string!`) but IMO it's much more explicit (or rather self-explanatory) to use a separate flag for that

**Comment by mhsdesign** [comment]
would it make sense to be able to check beforehand from userland as api, if the soft constrains of a command are met? would really help me in the nodeCreation template thingy ^^, and we could leverage the same api for ajax

edit: for the nodeTemplates usecase: no as the parent is not created yet.

**Comment by bwaidelich** [comment]
We just talked about this with @mhsdesign and @dlubitz in our weekly.

The behavior of the `PropertyCollectionInterface` is not fully defined unfortunately, but my preference would be this:

* Add a `required` flag to the node type schema (every property without that flag set to `true` is nullable)
* `iterator_to_array(node.properties)` returns an array with one entry for every property *in the node type schema*
  *  that means, that it might include properties with a value of `null`
  * ...and that it would *not include* properties that are stored in the db but not part of the schema (e.g. if they have been renamed or dropped without structure adjustments)
* `node.getProperty('<propertyName>')`:
  * if `<propertyName>` not defined in schema => `InvalidArgumentException` (currently it returns `null` which might also be OK)
  * otherwise: the deserialized value, wether its `null` or not
* `node.hasProperty('<propertyName>')`:
  * if `<propertyName>` not defined in schema => `false`
  * otherwise: `true`

**NOTE:** `SerializedPropertyValues` will still return all properties as persisted in the database (for structure adjustments etc.)

**UPDATE (2023-9-1):** As discussed in todays [weekly](https://neos-project.slack.com/docs/T04HF7TKV/F05NL5CE6E5) we decided, to keep the current behavior and let `PropertyCollection` return the (deserialized) values like they are stored in the db (not verifying schema compliance)

**Comment by mhsdesign** [comment]
And we have to kill https://github.com/neos/neos-ui/blob/a6d78fef508a3fd5dcaa397de746d0813bdfdff9/Classes/Domain/Service/NodePropertyConversionService.php#L26C7-L26C36

- automatic forgiving property mapping (eg no exceptions but null in case of failure) is not desired

**Comment by mhsdesign** [comment]
this issue is not super well structured and discusses many points.

I will split the discussion into sub issues:

- https://github.com/neos/neos-development-collection/issues/4631
- https://github.com/neos/neos-ui/issues/3608
