### ISSUE TITLE
Discussion: Should `ContentSubgraphInterface` know its `ContentSubgraphIdentity`?

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4327]
See discussion:

https://neos-project.slack.com/archives/C3MCBK6S2/p1684256748390969

I would find it helpful, when a subgraph could answer me all those things (a ContentSubgraphIdentity):

```
ContentRepositoryId $contentRepositoryId,
ContentStreamId $contentStreamId,
/**
 * DimensionSpacePoint a subgraph has been accessed in.
 */
DimensionSpacePoint $dimensionSpacePoint,
VisibilityConstraints $visibilityConstraints,
```

with this, i could "serialize" the subgraph and reconstruct it later, and the subgraph would be powerful enough to be passed around standalone as one could fetch the ContentRepository through the id -> unlimited power.
Currently one instead passes a node around, because it actually has the information about the `ContentSubgraphIdentity`

**Comment by bwaidelich** [comment]
Thanks for creating the issue.
Sorry for being stubborn and feel free to outvote me but since we'll have to support all APIs that we expose, I would really like to avoid YAGNI cases and understand the scenarios better in order to understand whether they should be solved differently.
"unlimited power" could also have been a reason to introducing `Node::setProperty()` back then ;)

Frankly, I don't see the same major issue with exposing the SG identity at all. But there is a reason why the `ContentRepository` does not expose its ID and so far whenever we wanted to add it, a different approach turned out to be better. So I would suggest to wait for the first concrete usecase at least – unless you already _have_ one at hand!?

**Comment by mhsdesign** [comment]
Indeed i have something in my mind. Inside a node creation handler of [node templates](https://github.com/Flowpack/Flowpack.NodeTemplates) pre neos 9 it was allowed to access the `triggeringNode` in eel expressions, (i used it to get its context to get a node by id)

With neos 9 this will change, we only have the intended node creation command at hand. But i dont want to pass it into eel as  this is a concept i dont want integrators to annoy with ^^ instead i was thinking about only building the subgraph and passing it as variable into eel.
Then eel helpers could use it to fetch nodes and additionally access for example the current node type manager and the cr and all things needed for (unplanned/edgecasy) extensibility and features. (All those unplanned features are already possible pre 9.0 and 9.0 will already force a big mind shift but i dont want to limit extensibility to drastically ;))

Sure enough i didnt had this excact use for know but i like neos for its extensibility and would like to make it a norm to have the `${subgraph}` in eel more often available, in cases where you dont have a node at hand or when you want to hide information.

Alternatively i could just pass the `subgraphIdentity` separately into eel, but i dislike this.
