### ISSUE TITLE
Do not use PositionalArraySorter to sort Projections config array

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-development-collection#4437]

**Comment by skurfuerst** [comment]
Related: #4289

**Comment by mhsdesign** [comment]
sorry i dont get the _why_ ^^

**Comment by bwaidelich** [comment]
> sorry i dont get the why ^^

@mhsdesign why we added it or why we should remove it?

I can explain both:
1. We _added_ it because we had interdependent projections.
2. You should _not_ have interdependent projections. So we removed the last one with #4411
3. User-ordered projections give the impression that you _may_ create interdependent projections but... see 2. :)
