### ISSUE TITLE
FEATURE: re-implement node:migrationcreate command for Neos 9

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-development-collection#4458]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

The `./flow node:migrationcreate` command that has been introduced with #4038 for Neos 8.3 needs too be adjusted to work in Neos 9. Since the package structure in Neos 9 is different, it should be discused in which package the command should be implemented.

**Comment by skurfuerst** [comment]
Hey everybody,

the question from @ahaeslich : 

> to be honest: I'm asking myself why there is Neos.ContentRepository.NodeMigration  and the Command is located in Neos.ContentRepositoryRegistry

The reason is that Neos.ContentRepository.NodeMigration is not a Flow package, but a generic Composer package (usable without Neos or Flow). Thus this package cannot contain Flow commands.

The "bridge" to Flow is Neos.ContentRepositoryRegistry (which is a Flow package, so it contains Flow specific things like CLI commands.

All the best, Sebastian

**Comment by crydotsnake** [comment]
> Hey everybody,
> 
> the question from @ahaeslich :
> 
> > to be honest: I'm asking myself why there is Neos.ContentRepository.NodeMigration  and the Command is located in Neos.ContentRepositoryRegistry
> 
> The reason is that Neos.ContentRepository.NodeMigration is not a Flow package, but a generic Composer package (usable without Neos or Flow). Thus this package cannot contain Flow commands.
> 
> The "bridge" to Flow is Neos.ContentRepositoryRegistry (which is a Flow package, so it contains Flow specific things like CLI commands.
> 
> All the best, Sebastian

Hello Sebastian

thanks for your feedback! i remember now you mentioned this already in one of your presentations about the ES CR :)

So i will do the same with my `./flow node:migrationcreate` command. What do you think?
