### ISSUE TITLE
9.0 Node property is set to null instead of unset in database

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4467]
related https://github.com/neos/neos-development-collection/issues/4304

this comment says that we treat null as unset, but i found out that this is not entirely true ;)
https://github.com/neos/neos-development-collection/blob/782b9585bb53f71a326c99c9fbf85671418f91ef/Neos.ContentRepository.Core/Classes/Feature/NodeModification/Event/NodePropertiesWereSet.php#L32-L33

creating a node and setting in the initial properties a defined property `foo` to `null` will show up in the CR explicitly.

**Comment by mhsdesign** [comment]
it seems @nezaniel touched the code the last time https://github.com/neos/neos-development-collection/commit/7b915a4afeea55a7fd7525e110e0c5d42b819e54 - is this current behavior intentional and why? ^^

**Comment by bwaidelich** [comment]
As discussed in [todays weekly](https://neos-project.slack.com/docs/T04HF7TKV/F05NL5CE6E5) I would recommend to **not make a difference whether a property wasn't set initially or whether it was removed lateron**.
While it might be useful to expose this information at some point, we should do so _explicitly_ and not via the `null`-behavior of some adapter.

Personally I would prefer to _unset_ properties in the db to better reflect the above. But since this would be purely _internal_ we could also keep the `null` value to allow for some future mitigation.

Regarding an equivalent for
```
node:repair --only addMissingDefaultValues
```
I would suggest to go for a more explicit migration anyways (filter for node type && current property value => set new value)
