### ISSUE TITLE
BUG: ContentRepository queries should sort consistenly by position

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-development-collection#4769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### affected parts (as identified)

- [] createChildNodeAggregateQuery
- [] findRootNodeAggregates

### Current Behavior

As #4768 shows the CI is currently broken as the changes in DB collations uncovered a bug in at least the implementation of `createChildNodeAggregateQuery` for the DBAL adapter, which currently ignores the `position` in the hierachyrelation projection which indicates the correct ordering of children.

**NOTE**: `createChildNodeAggregateQuery` is appeneded internally with more `WHERE` clauses in other parts of the code, so the sorting cannot simply be added in this method.

### Expected Behavior

The `position` is taken into account and nodes are consistently retrieved in the order they are supposed to be according to the events.

### Steps To Reproduce

See linked PR above, although due to the non deterministic behavior implemented at the moment, no certain fail can be produced.

### Environment

```markdown
- Flow: 9.0
- Neos: 9.0
- PHP: 8.2
```

### Anything else?

We can only speculate why this error has not emerged until now. My working assumption is that the sorting was based on some primary key that by chance resulted in the correct ordering, but does no longer with the new collation.

**Comment by bwaidelich** [comment]
We couldn't figure out what exactly led to the "regression", but it most probably is related to #4730 – in the best sense possible: The breaking tests showed us where we falsely expected a deterministic behavior.

The actual bug was two-fold:
* The `position` column of the hierarchy relation table is not respected in all cases
* The Behat tests partially expect nodes or DSPs to be of a certain order where they are actually non-deterministic

Both are fixed with #4770 (and #4771 provides a cosmetic follow-up that makes the code easier to read and maintain)

**Comment by mhsdesign** [comment]
So this can be closed right?
