### ISSUE TITLE
Overhaul ContentCacheFlusher

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#5175]
At the moment the ContentCacheFlusher can't flush caches discarded nodes. This seems to be caused by the fact, that after persisting the change (discard), the ContentCacheFlusher tries to identify his parents, which is not possible anymore.

To solve this issue, we need to do all node traversing operation BEFORE the persistence. Which should be done in the GraphProjectorCatchUpHookForCacheFlushing. So the ContentCacheFlusher does not need to do any node traversing anymore and simply flush all given caches.

Currently this doesn't have a effect, as the cacheEntryIdentifier is based on the contentStreamId, which leads to orphan cache entries after each new contentStream creation. On the other hand, the cache entry is not used anymore after discard, which means the same as a cache flush of the entry.

See also:
* https://neos-project.slack.com/archives/C04PYL8H3/p1718800219964049
* https://github.com/neos/neos-development-collection/issues/5150
* https://github.com/neos/neos-development-collection/pull/5163
* https://github.com/neos/neos-development-collection/pull/5155
* https://github.com/neos/neos-development-collection/pull/5160

**Comment by mhsdesign** [comment]
I just have some followup question if i may ^^ so all our decisions are documented for the future :D

Now we have the capability to flush a whole workspace if we want which is really powerful. 

1.) What was the reasoning against more fine grained flushing on `WorkspaceWasDiscarded` like only flushing all discarded nodes? Sure it would definitely require a dependency to the ChangeProjection as drawn out [here](https://github.com/neos/neos-development-collection/pull/5155) but that would allow to keep parts of the cache entries and thus optimise performance right?

2.) Also i played around to optimise `DiscardIndividualNodes` by trying to flush `$eventInstance->discardedNodes` but as found out by wilhelm in slack we cannot fetch the node aggregate - not even in `onBeforeEvent` because the content stream is already long gone. Question is will that haunt us in the long term? (This is also manifested in the codebase https://github.com/neos/neos-development-collection/blob/d38fd9d5e53aca307899a3d9697ea98bfd7dd1e5/Neos.ContentRepository.Core/Classes/Feature/WorkspaceCreation/Event/WorkspaceWasCreated.php#L29)

> I 've got "Discard All" working, but one problem remains: On DiscardIndividualNodes, the WorkspaceCommandHandler removes the old content stream before the WorkspaceWasPartiallyDiscarded event is emitted. This makes it impossible to flush the content cache for the affected nodes. I think it'd be safe to change the order of events there, but this would brake the convention used in that class. Any ideas/opinions?


3. Should we also flush on workspace deletion (`WorkspaceWasRemoved`)?


Edit i might actually recall us saying that discard is not that important to optimise as it will happen not that often.... and maybe optimising rebase will rather be worth our brain power.

**Comment by dlubitz** [comment]
1) The WorkspaceWasDiscarded event has no information about the discarded nodes. I don't know if it's worth to optimize this by making it more complex and also cache flushing itself is an expensive operation.

2) Simplicity. We wanted to keep it easy. Also the performance is dependent on the amount of discarded node. If you need to discard more single nodes, this is more expensive than the workspace flush.

3) Yeah, maybe. Didn't tought about this. But nothing urgent for the release.
