### ISSUE TITLE
Adopting dimension and auto-created child nodes conflict

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#782]
Jira issue originally created by user @kdambekalns:

Steps to reproduce
1. you have a site with multiple languages
2. you have a document node that has another document as autocreated child node
3. you select that child node and switch the language, answering "yes, copy"

-> you get a duplicate key error.
-> assumption: the parent is copied, the child autocreated, then copied, duplicate.

 Jira-URL: https://jira.neos.io/browse/NEOS-1090

**Comment by kdambekalns** [comment]
Uh, that's an old issue… but I was just about to open a potential duplicate, I think.

My case: `adoptNode` finds a node that does not yet exist in the needed dimensions and creates it, the auto-created children of that node are created as well. *But* those do exist (and everything worked so far, since the node that is being created has been "filled in" from a fallback so far) and I get a duplicate key error.

I wokred around it in `createVariantForContext` by checking for existence of the children to be created after the variant of their parent has been set up. Seems to work, I'll create a PR next week…
