### ISSUE TITLE
Using RequireJS causes backend crash

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#818]
Jira issue originally created by user @gerhard-boden:

when using requirejs in the frontend the loading of two javascript (core) files in the backend fails (see screenshot) resulting in broken inline editing.

I found this commit that states to fix the issue: https://review.typo3.org/#/c/26487/ 
Maybe the bug came up again because of changes somewhere around 1.2.5?

UPDATE 03.11.2015:
The problem can be fixed by using an older version of requireJS (http://requirejs.org/docs/release/2.1.9/minified/require.js)

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12137/editor.jpg) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1308

**Comment by kitsunet** [comment]
Will close as won't fix as this will probably not happen before the react UI.

**Comment by kdambekalns** [comment]
Because I looked for it, the change mentioned seems to be https://github.com/neos/neos-development-collection/commit/9eabd2384dab9304e14fbe00d2b3f4a3707671d6. See https://forge.typo3.org/issues/48074 (still up and running!)

Another related commit would be https://github.com/neos/neos-development-collection/commit/13f04acad8477aaed1ccab80b537a286d114ba29
