### ISSUE TITLE
Consistent behavior of node structure across content dimensions

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-development-collection#981]
Jira issue originally created by user @hlubek:

The node structure (per workspace) should always be consistent across different content dimensions. For a more consistent and reliable behavior we should not allow a different path for a node in different dimensions.

Reasons:
- A moved node in one dimension might belong to another node and the user is not aware of the connection
- Shine-through nodes from dimensions with a different structure are not considered correctly with a path-based query, which leads to unexpected results
  
  Jira-URL: https://jira.neos.io/browse/NEOS-369

**Comment by kitsunet** [comment]
I believe that is our current behavior with a lot of moving logic in Nodes... Closing for now.

**Comment by hlubek** [comment]
Actually the same structure structure for variants is forced for "aggregate" nodes (speak Document nodes), for non-aggregate nodes (Content) the structure & sorting for variants can be different.

So path-based queries for these nodes could not work as expected, but they should rarely be used for this purpose and will likely be deprecated with the new Content Repository (because we might have a different concept for node names and no stored paths).
